FROM pytorch/torchserve:latest
# Install dependencies (pandas, numpy, pypi-json)
RUN pip install --upgrade pip
RUN pip install pandas numpy pypi-json 

# docker build -t localhost:32000/mytorchserve:registry .
# docker push localhost:32000/mytorchserve