version: '3.8'
services:
  torchserve: 
    image: ciao:latest
    container_name: torchserve
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ./shared:/home/model-server/shared

      # don't work... see more to resovle this issue:
      # for this you must create a logs folder in the same directory as docker-compose.yml and in the logs folder create:
      # - config subfolder
      # - access_log.log
      # - model_log.log
      # - model_metrics.log
      # - ts_log.log
      # - ts_metrics.log
      # - ./logs:/home/model-server/logs 
    environment:
      - MODEL_STORE=/home/model-server/shared/model_store

    
    networks:
      - app_net

networks:
  app_net:
    driver: bridge