apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-torchserve
  labels:
    type: torchserve
  namespace: torchserve-cluster
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    # directory location on host (microk8s)
    path: /home/mechlav/work/PyTorchServing/kubernetes/shared
    # path: <path-to-PyTorchServing>/PyTorchServing/kubernetes/shared/