apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-nfs
  labels:
    type: torchserve
  namespace: torchserve-cluster
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
