apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-torchserve
  labels:
    type: torchserve
  namespace: torchserve-cluster
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
